/* Common */
export const SAVE = 'SAVE ';
export const REGISTER = 'REGISTER';
export const SET_ERRORS = 'SET_ERRORS';
export const CHANGE_FIELD = 'CHANGE_FIELD';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

/* User specific */
export const VALIDATE_USER = 'VALIDATE_USER';
export const VALIDATE_USER_LOGIN = 'VALIDATE_USER_LOGIN';
export const VALIDATE_USER_PROFILE = 'VALIDATE_USER_PROFILE';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const CHANGE_USER_PROFILE_ADDRESS_FIELD = 'CHANGE_USER_PROFILE_ADDRESS_FIELD';
export const CHANGE_USER_PROFILE_PHONE_FIELD = 'CHANGE_USER_PROFILE_PHONE_FIELD';

/* Enterprise specific */
export const VALIDATE_ENTERPRISE = 'VALIDATE_ENTERPRISE';
export const VALIDATE_ENTERPRISE_PROFILE = 'VALIDATE_ENTERPRISE_PROFILE';

export const ENTERPRISE_REGISTER_ERROR = 'ENTERPRISE_REGISTER_ERROR';
export const ENTERPRISE_REGISTER_PENDING = 'ENTERPRISE_REGISTER_PENDING';
export const ENTERPRISE_REGISTER_SUCCESS = 'ENTERPRISE_REGISTER_SUCCESS';

export const CHANGE_ENTERPRISE_PROFILE_ADDRESS_FIELD = 'CHANGE_ENTERPRISE_PROFILE_ADDRESS_FIELD';
export const CHANGE_ENTERPRISE_PROFILE_PHONE_FIELD = 'CHANGE_ENTERPRISE_PROFILE_PHONE_FIELD';

/* Status specific */
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_I18N = 'SET_I18N';
export const HANDLE_MENU = 'HANDLE_MENU';
export const CHANGE_STATE = 'CHANGE_STATE';
export const CHECK_SESSION = 'CHECK_SESSION';
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
export const CHANGE_RESPONSE = 'CHANGE_RESPONSE';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_EMPTY_STATE = 'SET_EMPTY_STATE';
export const HANDLE_GOOGLE_LOGIN = 'HANDLE_GOOGLE_LOGIN';
export const ENQUEUE_NOTIFICATION = 'ENQUEUE_NOTIFICATION';
export const SET_CHECKBOX_FORM = 'SET_CHECKBOX_FORM';
export const INVALIDATE_CHECKBOX_FORM = 'INVALIDATE_CHECKBOX_FORM';
export const SET_SNACKBAR_ENQUEUER = 'SET_SNACKBAR_ENQUEUER';

/* Navigation specific */
export const SET_NAVIGATION_LIST = 'SET_NAVIGATION_LIST';
export const SET_STATE_FORMS_REQUEST_JSON = 'SET_STATE_FORMS_REQUEST_JSON';
export const SET_ENTERPRISE_STATUS = 'SET_ENTERPRISE_STATUS';
export const SET_STATE_NESTED_FIELD_LEVEL_TWO = 'SET_STATE_NESTED_FIELD_LEVEL_TWO';

/* MX */
export const SET_FIELD_NESTED = 'SET_FIELD_NESTED';
export const CLEAR_ENTERPRISE_STATUS = 'CLEAR_ENTERPRISE_STATUS';
export const ADD_UPLOAD_FILES = 'ADD_UPLOAD_FILES';
export const ADD_UPLOAD_FILE = 'ADD_UPLOAD_FILE';
export const ADD_FIELD_COUNTRY_STATE = 'ADD_FIELD_COUNTRY_STATE';
export const ADD_FIELD_BENEFICIARY_LIST = 'ADD_FIELD_BENEFICIARY_LIST';
export const ADD_FIELD_PRINCIPAL_INCOME = 'ADD_FIELD_PRINCIPAL_INCOME';
export const ADD_FIELD_COMPANY_SHARESHOLDER = 'ADD_FIELD_COMPANY_SHARESHOLDER';
export const ADD_FIELD_COUNTRY_STATE_INFLUENCE = 'ADD_FIELD_COUNTRY_STATE_INFLUENCE';
export const ADD_FIELD_GUBERNAMENTAL_DEPENDENCY = 'ADD_FIELD_GUBERNAMENTAL_DEPENDENCY';
export const ADD_FIELD_VULNERABLE_CUSTOMERS_ACTIVITY = 'ADD_FIELD_VULNERABLE_CUSTOMERS_ACTIVITY';
export const SET_EMPTY_STATE_FINANTIAL_INSTITUTION_QUESTIONNAIRE =
  'SET_EMPTY_STATE_FINANTIAL_INSTITUTION_QUESTIONNAIRE';
export const SET_EMPTY_STATE_FINANTIAL_INSTITUTION_QUESTIONNAIRE_CUMPLO =
  'SET_EMPTY_STATE_FINANTIAL_INSTITUTION_QUESTIONNAIRE_CUMPLO';
export const SET_EMPTY_STATE_CREDIT_AND_INCOMES_ANNEX = 'SET_EMPTY_STATE_CREDIT_AND_INCOMES_ANNEX';
export const SET_EMPTY_STATE_POLITICALLY_EXPOSED_PERSON_ANNEX = 'SET_EMPTY_STATE_POLITICALLY_EXPOSED_PERSON_ANNEX';
export const SET_EMPTY_STATE_PUBLIC_OFFICIAL_ANNEX = 'SET_EMPTY_STATE_PUBLIC_OFFICIAL_ANNEX';
export const SET_EMPTY_STATE_RISKY_INFORMATION_QUESTIONNAIRE = 'SET_EMPTY_STATE_RISKY_INFORMATION_QUESTIONNAIRE';
export const SET_EMPTY_STATE_VULNERABLE_ACTIVITY_ANNEX = 'SET_EMPTY_STATE_VULNERABLE_ACTIVITY_ANNEX';
/* CHANGES */
export const CHANGE_FIELD_NESTED = 'CHANGE_FIELD_NESTED';
export const CHANGE_FIELD_RISKY_COUNTRY = 'CHANGE_FIELD_RISKY_COUNTRY';
export const CHANGE_FIELD_NESTED_TWO_LEVEL = 'CHANGE_FIELD_NESTED_TWO_LEVEL';
export const CHANGE_FIELD_BENEFICIARY_LIST = 'CHANGE_FIELD_BENEFICIARY_LIST';
export const CHANGE_FIELD_COMPANY_SHARESHOLDER = 'CHANGE_FIELD_COMPANY_SHARESHOLDER';
export const CHANGE_FIELD_COUNTRY_STATE_INFLUENCE = 'CHANGE_FIELD_COUNTRY_STATE_INFLUENCE';
export const CHANGE_FIELD_FINANTIAL_INSTITUTION_QUEST = 'CHANGE_FIELD_FINANTIAL_INSTITUTION_QUEST';
export const CHANGE_FIELD_VULNERABLE_ACTIVITY_QUESTIONS = 'CHANGE_FIELD_VULNERABLE_ACTIVITY_QUESTIONS';
export const CHANGE_FIELD_VULNERABLE_CUSTOMERS_ACTIVITY_ITERATION =
  'CHANGE_FIELD_VULNERABLE_CUSTOMERS_ACTIVITY_ITERATION';
/* INITIALIZE */
export const INITIALIZE_FINANTIAL_INSTITUTION_QUEST = 'INITIALIZE_FINANTIAL_INSTITUTION_QUEST';
export const INITIALIZE_VULNERABLE_ACTIVITY_QUESTIONS = 'INITIALIZE_VULNERABLE_ACTIVITY_QUESTIONS';
export const INITIALIZE_RISKY_INFORMATION_QUESTIONNAIRE_MX = 'INITIALIZE_RISKY_INFORMATION_QUESTIONNAIRE_MX';
/* DELETE */
export const WILL_DELETE_PARENT_CHILD = 'WILL_DELETE_PARENT_CHILD';
export const DELETE_NAVIGATION_ITEM = 'DELETE_NAVIGATION_ITEM';
export const DELETE_FIELD_UPLOADED_FILE = 'DELETE_FIELD_UPLOADED_FILE';
export const DELETE_FIELD_NESTED_TWO_LEVEL = 'DELETE_FIELD_NESTED_TWO_LEVEL';
export const DELETE_FIELD_NESTED_THREE_LEVEL = 'DELETE_FIELD_NESTED_THREE_LEVEL';
/* VALIDATION */
export const VALIDATE_GROUP = 'VALIDATE_GROUP';
export const VALIDATE_PUBLIC_OFFICIAL_ANNEX = 'VALIDATE_PUBLIC_OFFICIAL_ANNEX';
export const VALIDATE_CREDIT_AND_INCOMES_ANNEX = 'VALIDATE_CREDIT_AND_INCOMES_ANNEX';
export const VALIDATE_VULNERABLE_ACTIVITY_ANNEX = 'VALIDATE_VULNERABLE_ACTIVITY_ANNEX';
export const VALIDATE_RISKY_INFORMATION_QUESTIONNAIRE = 'VALIDATE_RISKY_INFORMATION_QUESTIONNAIRE';
export const VALIDATE_POLITICALLY_EXPOSED_PERSON_ANNEX = 'VALIDATE_POLITICALLY_EXPOSED_PERSON_ANNEX';
export const VALIDATE_FINANTIAL_INSTITUTION_QUESTIONNAIRE = 'VALIDATE_FINANTIAL_INSTITUTION_QUESTIONNAIRE';
export const VALIDATE_FINANTIAL_INSTITUTION_QUESTIONNAIRE_CUMPLO =
  'VALIDATE_FINANTIAL_INSTITUTION_QUESTIONNAIRE_CUMPLO';
export const INVALIDATE_NAVIGATION_LIST = 'INVALIDATE_NAVIGATION_LIST';

export const CHANGE_CUMPLO_EXTERNAL_ID = 'CHANGE_CUMPLO_EXTERNAL_ID';

/* Group specific */
export const ADD_GROUP_ASSOCIATION = 'ADD_GROUP_ASSOCIATION';

/* External Request specific */
export const LOAD_EXTERNAL_REQUEST_DETAIL = 'LOAD_EXTERNAL_REQUEST_DETAIL';

/* Investment Simulation specific */
export const LOAD_INVESTMENT_SIMULATION_MODAL = 'LOAD_INVESTMENT_SIMULATION_MODAL';
export const CLOSE_INVESTMENT_SIMULATION_MODAL = 'CLOSE_INVESTMENT_SIMULATION_MODAL';
export const PENDING_INVESTMENT_SIMULATION_MODAL = 'PENDING_INVESTMENT_SIMULATION_MODAL';
export const SET_ENTERPRISE_ID = 'SET_ENTERPRISE_ID';
export const SET_PERSON_ID = 'SET_PERSON_ID';
export const LOAD_INVESTMENT_COSTS = 'LOAD_INVESTMENT_COSTS';

/* Internal Request specific */
export const LOAD_INTERNAL_REQUEST_DETAIL = 'LOAD_INTERNAL_REQUEST_DETAIL';
export const SET_STATE_NESTED_FIELD = 'SET_STATE_NESTED_FIELD';
export const SET_BACKUP_DETAIL_DATA = 'SET_BACKUP_DETAIL_DATA';
export const SET_EMPTY_STATE_BACKUPS = 'SET_EMPTY_STATE_BACKUPS';
export const LOAD_BACKUP_DATA = 'LOAD_BACKUP_DATA';

/* Loan Calculator */
export const SET_LOAN_CALCULATOR_TEMPLATE = 'SET_LOAN_CALCULATOR_TEMPLATE';
export const SET_STATE_NESTED_FIELD_LEVEL_ONE = 'SET_STATE_NESTED_FIELD_LEVEL_ONE';
export const SET_STATE_NESTED_FIELD_LEVEL_THREE = 'SET_STATE_NESTED_FIELD_LEVEL_THREE';
export const ADD_FIELD_LOAN_COSTS = 'ADD_FIELD_LOAN_COSTS';
export const CHANGE_FIELD_LOAN_CALCULATOR_COST = 'CHANGE_FIELD_LOAN_CALCULATOR_COST';
export const CHANGE_FIELD_LOAN_CURRENCY = 'CHANGE_FIELD_LOAN_CURRENCY';
export const ADD_FIELD_LOAN_PERIOD = 'ADD_FIELD_LOAN_PERIOD';
export const DELETE_FIELD_LOAN_PERIOD = 'DELETE_FIELD_LOAN_PERIOD';
export const CHANGE_FIELD_NESTED_FOUR_LEVEL = 'CHANGE_FIELD_NESTED_FOUR_LEVEL';
export const CHANGE_FIELD_NESTED_ONE_LEVEL = 'CHANGE_FIELD_NESTED_ONE_LEVEL';
export const CHANGE_LOAN_RESULT = 'CHANGE_LOAN_RESULT';
export const CLEAN_LOAN_RESULT = 'CLEAN_LOAN_RESULT';
export const VALIDATE_LOAN_CALCULATOR = 'VALIDATE_LOAN_CALCULATOR';

// miscellaneous
export const CHANGE_TAB = 'CHANGE_TAB';
export const CLEAN_FULL_STORE = 'CLEAN_FULL_STORE';

/* Bank Account */
export const STORE_BANK_ACCOUNT_DETAILS = 'STORE_BANK_ACCOUNT_DETAILS';
export const VALIDATE_BANK_ACCOUNT_DETAILS = 'VALIDATE_BANK_ACCOUNT_DETAILS';

/* CURSE */
export const PUSH_ITEM_TO_ARRAY = 'PUSH_ITEM_TO_ARRAY';
export const REMOVE_ITEM_FROM_ARRAY = 'REMOVE_ITEM_FROM_ARRAY';
export const SET_UPLOADER_ID = 'SET_UPLOADER_ID';
export const SET_LIST = 'SET_LIST';
export const UNSET_LIST = 'UNSET_LIST';
export const CHANGE_FIELD_NESTED_LIST = 'CHANGE_FIELD_NESTED_LIST';
export const SET_EMPTY_STATE_BANKACCOUNTS = 'SET_EMPTY_STATE_BANKACCOUNTS';
